services:
  review:
    build: .
    environment:
      - TZ=Asia/Tokyo
      - CLICOLOR=1
      - CLICOLOR_FORCE=1
    volumes:
      - .:/librarian
    tty: true
  resources:
    image: nginx:1.27.4
    volumes:
      - ./shelves:/usr/share/nginx/html/shelves
