name: CI

on:
  push:
    branches: ['main', 'ci-*']
    paths-ignore: ['**.md']
  pull_request:
    branches: ['main']
    paths-ignore: ['**.md']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
